n=0:1:31;
x1=sin(pi.*n./4).*cos(pi.*n./4);
x2=(cos(pi.*n./4)).^2;
x3=sin(pi.*n./4).*cos(pi.*n./8);
subplot(3, 1, 1);
stem(n,x1);
title('sin(\pin/4)cos(\pin/4)');
xlabel('n');
ylabel('x_1[n]');
subplot(3, 1, 2);
stem(n,x2);
title('cos(\pin/4)^2');
xlabel('n');
ylabel('x_2[n]');
subplot(3, 1, 3);
stem(n,x3);
title('sin(\pin/4)cos(\pin/8)');
xlabel('n');
ylabel('x_3[n]');