@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Oct 15 20:12:04 +0800 2023
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim adder_4bits_tb_time_impl -key {Post-Implementation:sim_1:Timing:adder_4bits_tb} -tclbatch adder_4bits_tb.tcl -log simulate.log"
call xsim  adder_4bits_tb_time_impl -key {Post-Implementation:sim_1:Timing:adder_4bits_tb} -tclbatch adder_4bits_tb.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
